import React from "react";
import classes from "./AboutPage.module.css";
import globalClasses from "../../styles/Global.module.css";
import Myprofile from "../../assets/about/team-3.jpg";
import Image from "next/image";
import Link from "next/link";
import SayHelloSection from "@/components/SayHelloSection/SayHelloSection";
import Head from "next/head";
 
const AboutPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={globalClasses.container}>
        <div className={classes.aboutContainer}>
          <div className={classes.aboutMeContainer}>
            <div className={classes.aboutMeTextWrapper}>
              <p>
                Hi! My name is Thierno Barry, I am a full stack website
                developer based in Belgium.
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde
                voluptates facere fuga labore repudiandae, cum necessitatibus
                quasi in temporibus dolore eius quaerat dignissimos tenetur
                beatae magni neque. Iste, molestiae earum!
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde
                voluptates facere fuga labore repudiandae, cum necessitatibus
                quasi in temporibus dolore eius quaerat dignissimos tenetur
                beatae magni neque. Iste, molestiae earum!
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde
                voluptates facere fuga labore repudiandae, cum necessitatibus
                quasi in temporibus dolore eius quaerat dignissimos tenetur
                beatae magni neque. Iste, molestiae earum!
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde
                voluptates facere fuga labore repudiandae, cum necessitatibus
                quasi in temporibus dolore eius quaerat dignissimos tenetur
                beatae magni neque. Iste, molestiae earum!
              </p>
            </div>
            <Image
              src={Myprofile}
              alt="Thierno"
              className={classes.aboutMeImage}
            />
          </div>
          <Link href="/contact" className={classes.checkOutCV}>
            Check out my CV
          </Link>
        </div>
        <SayHelloSection />
      </main>
    </>
  );
};

export default AboutPage;
