import React from "react";
import classes from "./AboutPage.module.css";
import globalClasses from "../../styles/Global.module.css";
import Myprofile from "../../assets/about/team-3.jpg";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import SayHelloSection from "@/components/SayHelloSection/SayHelloSection";

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={globalClasses.container}>
        <div className={classes.aboutContainer}>
          <div className={classes.aboutMeContainer}>
            <div className={classes.aboutMeTextWrapper}>
              <p>
                Hi! My name is Thierno Barry, I am a full stack website
                developer based in Belgium.
              </p>
              <p>
                I am passionate about creating digital content for the web. My
                interest in web development was sparked in 2020 when I created
                my first project called Diarabaka. a blog app built using React
                Noide.js.
              </p>
              <p>
                Fast-forward to today. I specialize in designing and developing
                high-quality solutions that delight our clients and exceed their
                expectations at Becode.
              </p>
              <p>
                Additionally. I share my knowledge and passion with the world
                through my Blog, where I demonstrate how to build fullstack
                applications.
              </p>
              <p>
                I am also working on a new project called Diarabaka, aimed at
                enchancing frontend development skills.
              </p>
              
            </div>
            <Image
              src={Myprofile}
              alt="Thierno"
              className={classes.aboutMeImage}
            />
          </div>
          <Link href="/contact" className={classes.checkOutCV}>
            Check out my CV
          </Link>
        </div>
        <SayHelloSection />
      </main>
    </>
  );
};

export default AboutPage;
