import Head from "next/head";
import SayHelloSection from "@/components/SayHelloSection/SayHelloSection";
import WelcomeSection from "@/components/WelcomeSection/WelcomeSection";

export default function Home() {
  return (
    <>
      <Head>
      <title>Thierno&lsquo;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tmb.jpg" />
      </Head>
      <>
        <WelcomeSection />
        <SayHelloSection />
      </>
    </>
  );
}
